# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Unzip the dataset and get the environment ready
"""

# 1. Install YOLOv11 dependencies
!pip install ultralytics

# 2. Extract the dataset to the specified folder
import zipfile
import os

zip_path = '/content/japanese_textiles.zip'
extract_path = '/content/dataset'

if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print(f"Dataset successfully extracted to: {extract_path}")
else:
    print(f"File not found: {zip_path}. Please verify the path is correct.")

"""自动化结构整理与生成 data.yaml"""

import os
import glob
import shutil
import random
import yaml

# Define original extraction path and target directory
base_src_dir = '/content/dataset/japanese_textiles'
target_base_dir = '/content/dataset/split_data'

# Define standard YOLO subdirectories
sub_dirs = [
    'images/train', 'images/val',
    'labels/train', 'labels/val'
]
for sub_dir in sub_dirs:
    os.makedirs(os.path.join(target_base_dir, sub_dir), exist_ok=True)

# 1. Automatically locate and analyze dataset format
# Check for image files (.jpg, .jpeg, .png)
image_extensions = ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']
all_images = []
for ext in image_extensions:
    all_images.extend(glob.glob(os.path.join(base_src_dir, '**', ext), recursive=True))

if not all_images:
    print("❌ Error: No images found in the extraction path. Please check the folder contents!")
else:
    print(f"📊 Found a total of {len(all_images)} images. Analyzing whether it is a [Classification] or [Detection] dataset...")

    # Check for corresponding annotation files (.txt)
    all_txts = glob.glob(os.path.join(base_src_dir, '**', '*.txt'), recursive=True)

    # Filter out non-annotation files like classes.txt
    label_txts = [f for f in all_txts if not f.endswith('classes.txt')]

    # --- Case A: Object Detection dataset (images and .txt annotations appear in pairs) ---
    if len(label_txts) > 0:
        print(f"Detected {len(label_txts)} text annotation files. Organizing into Object Detection (YOLO) format...")

        # Match images with their corresponding txt annotations to ensure valid pairs
        valid_pairs = []
        for img_path in all_images:
            base_name = os.path.splitext(img_path)[0]
            txt_path = base_name + '.txt'
            if os.path.exists(txt_path):
                valid_pairs.append((img_path, txt_path))

        # Shuffle and split (80% train, 20% val)
        random.seed(42)
        random.shuffle(valid_pairs)
        split_idx = int(len(valid_pairs) * 0.8)
        train_pairs = valid_pairs[:split_idx]
        val_pairs = valid_pairs[split_idx:]

        # Copy files
        for img, txt in train_pairs:
            shutil.copy(img, os.path.join(target_base_dir, 'images/train', os.path.basename(img)))
            shutil.copy(txt, os.path.join(target_base_dir, 'labels/train', os.path.basename(txt)))
        for img, txt in val_pairs:
            shutil.copy(img, os.path.join(target_base_dir, 'images/val', os.path.basename(img)))
            shutil.copy(txt, os.path.join(target_base_dir, 'labels/val', os.path.basename(txt)))

        # Attempt to retrieve class names
        classes_file = os.path.join(base_src_dir, 'classes.txt')
        if os.path.exists(classes_file):
            with open(classes_file, 'r') as f:
                classes = [line.strip() for line in f.readlines() if line.strip()]
        else:
            classes = ['pattern_class_0'] # Default fallback name

    # --- Case B: Pure Image Classification dataset (organized by folders, no .txt files) ---
    else:
        print("No .txt object detection annotation files detected. Classifying as an [Image Classification] dataset.")
        print("Automatically generating full-image 'virtual bounding boxes' (treating the whole image as a target class) for YOLO and MobileNet compatibility...")

        # Use subfolder names as classes
        subfolders = [f.name for f in os.scandir(base_src_dir) if f.is_dir()]
        if not subfolders:
            subfolders = ['default_textile']
            classes = subfolders
            class_to_idx = {subfolders[0]: 0}
            image_groups = {subfolders[0]: all_images}
        else:
            classes = subfolders
            class_to_idx = {name: idx for idx, name in enumerate(classes)}
            image_groups = {name: [] for name in classes}
            for img_path in all_images:
                folder_name = os.path.basename(os.path.dirname(img_path))
                if folder_name in image_groups:
                    image_groups[folder_name].append(img_path)

        # Split and generate labels
        for class_name, img_list in image_groups.items():
            class_idx = class_to_idx[class_name]
            random.seed(42)
            random.shuffle(img_list)
            split_idx = int(len(img_list) * 0.8)

            # Distribute files and write YOLO label format
            # (ClassID CenterX CenterY Width Height -> Normalized full image: idx 0.5 0.5 1.0 1.0)
            for i, img in enumerate(img_list):
                stage = 'train' if i < split_idx else 'val'
                img_name = os.path.basename(img)
                txt_name = os.path.splitext(img_name)[0] + '.txt'

                # Copy image
                shutil.copy(img, os.path.join(target_base_dir, f'images/{stage}', img_name))
                # Create a full-image bounding box label for YOLO compatibility
                with open(os.path.join(target_base_dir, f'labels/{stage}', txt_name), 'w') as f:
                    f.write(f"{class_idx} 0.5 0.5 1.0 1.0\n")

        # Keep a standard classification folder format for MobileNet
        shutil.copytree(base_src_dir, os.path.join(target_base_dir, 'classification'), dirs_exist_ok=True)

    # 2. Core: Dynamically write the data.yaml file
    yaml_path = '/content/dataset/data.yaml'

    yaml_data = {
        'path': target_base_dir,
        'train': 'images/train',
        'val': 'images/val',
        'names': {idx: name for idx, name in enumerate(classes)}
    }

    with open(yaml_path, 'w') as f:
        yaml.dump(yaml_data, f, default_flow_style=False)

    print("✅ Dataset organization complete!")
    print(f"✅ Successfully generated YOLOv11 configuration file: {yaml_path}")
    print(f"ℹ️ Extracted class list: {classes}")

"""运行调整路径后的 YOLOv11 训练Training YOLOv11 after adjusting the paths"""

from ultralytics import YOLO

# 1. Load a pretrained YOLOv11 Nano detection model
yolo_model = YOLO("yolo11n.pt")

# 2. Start training (directly reading the newly created yaml path)
yolo_results = yolo_model.train(
    data="/content/dataset/data.yaml",  # Path to the generated configuration file
    epochs=30,                          # 30 epochs for quick validation and comparison
    imgsz=640,
    batch=16,
    device="cuda"
)

print("YOLOv11 training complete!")

"""运行 MobileNet 训练（无缝衔接）Run MobileNet training (seamless transition)"""

import os
import glob
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms, models
from torch.utils.data import Dataset, DataLoader
from PIL import Image

# 1. Define a custom dataset class for loading images and YOLO labels
class TextileDataset(Dataset):
    def __init__(self, img_dir, transform=None):
        self.img_dir = img_dir
        self.transform = transform

        # Search for all image files in the directory
        self.img_paths = []
        for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']:
            self.img_paths.extend(glob.glob(os.path.join(img_dir, ext)))

        # Read class labels from corresponding YOLO annotation files
        self.labels = []
        for img_path in self.img_paths:
            # Convert image path to label path
            # Example:
            # images/train/img001.jpg -> labels/train/img001.txt
            label_path = img_path.replace('images', 'labels')
            label_path = os.path.splitext(label_path)[0] + '.txt'

            if os.path.exists(label_path):
                with open(label_path, 'r') as f:
                    first_line = f.readline().strip()
                    if first_line:
                        class_id = int(first_line.split()[0])
                        self.labels.append(class_id)
                    else:
                        self.labels.append(0)
            else:
                # Assign class 0 if no label file exists
                self.labels.append(0)

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img_path = self.img_paths[idx]
        image = Image.open(img_path).convert('RGB')
        label = self.labels[idx]

        if self.transform:
            image = self.transform(image)

        return image, label


# 2. Define data preprocessing and augmentation
data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225]
    )
])

# 3. Load training and validation datasets
train_dir = '/content/dataset/split_data/images/train'
val_dir = '/content/dataset/split_data/images/val'

train_dataset = TextileDataset(train_dir, transform=data_transforms)
val_dataset = TextileDataset(val_dir, transform=data_transforms)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

# Automatically determine the number of classes
all_labels = train_dataset.labels + val_dataset.labels
num_classes = len(set(all_labels)) if len(all_labels) > 0 else 1

print(
    f"MobileNet dataset loaded successfully!\n"
    f"Training samples: {len(train_dataset)}\n"
    f"Validation samples: {len(val_dataset)}\n"
    f"Detected classes: {num_classes}"
)

# 4. Build the MobileNetV3 model
mobilenet_model = models.mobilenet_v3_large(pretrained=True)

num_ftrs = mobilenet_model.classifier[3].in_features
mobilenet_model.classifier[3] = nn.Linear(
    num_ftrs,
    num_classes
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

mobilenet_model = mobilenet_model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(
    mobilenet_model.parameters(),
    lr=0.001
)

# 5. Train the model
print("Starting MobileNet training...")

num_epochs = 15

for epoch in range(num_epochs):

    mobilenet_model.train()
    running_loss = 0.0

    for inputs, labels in train_loader:

        inputs = inputs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = mobilenet_model(inputs)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)

    epoch_loss = (
        running_loss / len(train_dataset)
        if len(train_dataset) > 0
        else 0
    )

    print(
        f"Epoch {epoch + 1}/{num_epochs} "
        f"- Training Loss: {epoch_loss:.4f}"
    )

# 6. Save trained weights
torch.save(
    mobilenet_model.state_dict(),
    "mobilenet_textiles.pth"
)

print("Training completed successfully!")
print("Model weights saved as: mobilenet_textiles.pth")

"""Create a Gradio demo interface (comparison test)"""

# 1. Install Gradio if it is not already installed
!pip install gradio

import os
import gradio as gr
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
from ultralytics import YOLO

# ==========================================
# 1. Load the trained YOLOv11 model
# ==========================================
yolo_weight_path = "runs/detect/train-2/weights/best.pt"

if os.path.exists(yolo_weight_path):
    yolo_deployed = YOLO(yolo_weight_path)
    print("YOLOv11 model loaded successfully!")
else:
    import glob
    possible_paths = glob.glob("runs/detect/**/best.pt", recursive=True)

    if possible_paths:
        yolo_deployed = YOLO(possible_paths[-1])
        print(f"Warning: train-2 not found. Loading the latest weights instead:\n{possible_paths[-1]}")
    else:
        raise FileNotFoundError(
            "No trained YOLO weight (best.pt) was found. Please make sure the YOLO training has finished successfully."
        )

# ==========================================
# 2. Load the trained MobileNet model
# ==========================================
mobilenet_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225]
    )
])

mobilenet_weight_path = "mobilenet_textiles.pth"

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# Initialize MobileNetV3
mobilenet_deployed = models.mobilenet_v3_large(pretrained=False)

if os.path.exists(mobilenet_weight_path):

    # Load the saved state dictionary
    state_dict = torch.load(
        mobilenet_weight_path,
        map_location=device
    )

    # Automatically detect the number of output classes
    saved_classes = state_dict["classifier.3.weight"].shape[0]

    print(
        f"Detected number of classes from the trained model: {saved_classes}"
    )

    # Replace the final classifier layer
    num_ftrs = mobilenet_deployed.classifier[3].in_features

    mobilenet_deployed.classifier[3] = nn.Linear(
        num_ftrs,
        saved_classes
    )

    # Load trained weights
    mobilenet_deployed.load_state_dict(state_dict)

    mobilenet_deployed = mobilenet_deployed.to(device)
    mobilenet_deployed.eval()

    print("MobileNet model loaded successfully!")

else:
    print("Warning: mobilenet_textiles.pth was not found. MobileNet will use random weights.")

# ==========================================
# 3. Define the inference function
# ==========================================
def compare_models(input_image):

    if input_image is None:
        return None, "Please upload an image."

    pil_img = Image.fromarray(input_image).convert("RGB")

    # --------------------------------------
    # YOLOv11 Detection
    # --------------------------------------
    yolo_result = yolo_deployed(pil_img)

    yolo_output_img = yolo_result[0].plot()

    # --------------------------------------
    # MobileNet Classification
    # --------------------------------------
    if os.path.exists(mobilenet_weight_path):

        input_tensor = mobilenet_transforms(
            pil_img
        ).unsqueeze(0).to(device)

        with torch.no_grad():

            outputs = mobilenet_deployed(input_tensor)

            probabilities = torch.nn.functional.softmax(
                outputs[0],
                dim=0
            )

        best_prob, best_class = torch.max(
            probabilities,
            0
        )

        mobilenet_result = (
            f"MobileNet Prediction\n\n"
            f"Predicted Class ID: {best_class.item()}\n"
            f"Confidence Score: {best_prob.item() * 100:.2f}%"
        )

    else:

        mobilenet_result = (
            "MobileNet weights were not loaded. "
            "No classification result is available."
        )

    return yolo_output_img, mobilenet_result

# ==========================================
# 4. Launch the Gradio application
# ==========================================
demo = gr.Interface(
    fn=compare_models,

    inputs=gr.Image(
        label="Upload a Textile or Pattern Image"
    ),

    outputs=[
        gr.Image(
            label="YOLOv11 Pattern Detection"
        ),
        gr.Textbox(
            label="MobileNet Classification Result"
        )
    ],

    title="AI Pattern Recognition System (YOLOv11 vs MobileNet)",

    description=(
        "Upload a textile or pattern image. "
        "The system will simultaneously perform "
        "object detection using YOLOv11 and "
        "pattern classification using MobileNet."
    )
)

# Launch the application and generate a public link
demo.launch(
    share=True,
    debug=True
)